FROM openjdk:8-jdk-alpine

WORKDIR /usr/src/app

COPY . .

CMD [ "npm", "run", "start:prod" ]

# Port used for IDE debugging
EXPOSE 50505
ENTRYPOINT ["bash", "-c", "java -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=50505 -jar app.jar"]

COPY instructions/target/instructions-*.jar app.jar
